services:
  web:
    image: ghcr.io/azuracast/azuracast:development
    build:
      context: .
      target: development
    ports:
  - "8080:8080"
    environment:
      VAR_DUMPER_FORMAT: server
      VAR_DUMPER_SERVER: host.docker.internal:9912
    volumes:
      # Uncomment these lines if mounting a custom SSL cert (i.e. mkcert)
      # - $PWD/util/local_ssl/default.crt:/var/azuracast/storage/acme/custom.crt:ro
      # - $PWD/util/local_ssl/default.key:/var/azuracast/storage/acme/custom.key:ro
      - $PWD/node_modules:/var/azuracast/www/node_modules
      - $PWD/vendor:/var/azuracast/www/vendor
      - $PWD:/var/azuracast/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
